kblog/kblog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('okayama.urls')),
   path('', include('user_app.urls')), 
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kblog/okayama/urls.py
from django.urls import path
from . import views

app_name = 'okayama'
urlpatterns = [
   path('', views.index, name='index'),
   path('detail/<int:post_id>/', views.detail, name='detail'),
   path('add/', views.add, name='add'),
   path('edit/<int:post_id>/', views.edit, name='edit'),
   path('delete/<int:post_id>/', views.delete, name='delete'),
]

kblog/user_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user_app'
urlpatterns = [
  path('login/', auth_views.LoginView.as_view(template_name='user_app/login.html'), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.signup, name='signup'), 
  path('user/<int:user_id>/', views.detail, name='detail'),
  path('user/edit/<int:user_id>/', views.edit, name='edit'),
  path('user/delete/<int:user_id>/', views.delete, name='delete')
]

kblog/okayama/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
 #追加
class Tag(models.Model):
 tag = models.CharField('タグ名', max_length=50)
 def __str__(self):
   return self.tag

class Post(models.Model):
   title = models.CharField('タイトル', max_length=35)
   text = models.TextField('本文')
   image = models.ImageField('画像', upload_to = 'images', blank=True)
   created_at = models.DateTimeField('投稿日', default=timezone.now)
   tag = models.ForeignKey(Tag, verbose_name = 'タグ', on_delete=models.PROTECT)
   user = models.ForeignKey(User, on_delete=models.CASCADE)

   def __str__(self):
       return self.title

kblog/user_app/models.py
from django.db import models

# Create your models here.

kblog/okayama/forms.py
from django import forms
from .models import Post, Tag
from django.forms import ModelForm

class PostAddForm(forms.ModelForm):    
   class Meta:
       model = Post
       fields = ['title', 'text', 'image', 'tag']

kblog/user_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
  class Meta:
      model = User
      fields = ('username', 'email', 'password1', 'password2')

kblog/okayama/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Tag
from .forms import PostAddForm 
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
   posts = Post.objects.all().order_by('-created_at')
   return render(request, 'okayama/index.html', {'posts': posts})

def detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'okayama/detail.html', {'post': post})

@login_required
def add(request):
   if request.method == "POST":
      form = PostAddForm(request.POST, request.FILES)
      if form.is_valid():
         post = form.save(commit=False)
         post.user = request.user
         post.save()
         return redirect('okayama:index')
   else:   
       form = PostAddForm()
   return render(request, 'okayama/add.html', {'form': form})

@login_required
def edit(request, post_id):
   post = get_object_or_404(Post, id=post_id)
   if request.method == "POST":
       form = PostAddForm(request.POST, request.FILES, instance=post)
       if form.is_valid():
           form.save()
           return redirect('okayama:detail', post_id=post.id)
   else:
       form = PostAddForm(instance=post)
   return render(request, 'okayama/edit.html', {'form': form, 'post':post })

@login_required
def delete(request, post_id):
   post = get_object_or_404(Post, id=post_id)
   post.delete()
   return redirect('okayama:index')

kblog/user_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignUpForm
from django.contrib.auth import authenticate, login
from okayama .models import Post
from django.contrib.auth.models import User

# Create your views here.
def signup(request):
  signup_form = SignUpForm(request.POST or None)
  if request.method == "POST" and signup_form.is_valid():
      user = signup_form.save()
      input_username = signup_form.cleaned_data['username']
      input_email = signup_form.cleaned_data['email']
      input_password = signup_form.cleaned_data['password1']
      user = authenticate(username=input_username, email=input_email, password=input_password)
      login(request, user)
      return redirect('okayama:index')
  context = {
      "signup_form": signup_form,
  }
  return render(request, 'user_app/signup.html', context)

def detail(request, user_id):
   user = get_object_or_404(User, id=user_id)
   posts = user.post_set.all().order_by('-created_at')
   return render(request, 'user_app/detail.html', {'user': user, 'posts': posts})  

def edit(request, user_id):
   user = get_object_or_404(User, id=user_id)
   if request.method == "POST":
       form = SignUpForm(request.POST, instance=request.user)
       if form.is_valid():
           form.save()
           return redirect('user_app:detail', user_id=user.id)
   else:
       form = SignUpForm(instance=user)
   return render(request, 'user_app/edit.html', {'form': form, 'user':user })

def delete(request, user_id):
   user = get_object_or_404(User, id=user_id)
   user.delete()
   return redirect('okayama:index')

kblog/templates/base.html
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <meta name="description" content=""/>
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}"">

   <title>Blog</title>
 </head>
 <body>
    {% include 'header.html' %}
      {% block content %} 
      {% endblock %}  
    {% include 'footer.html' %}
     </body>
</html>

kblog/templates/footer.html
<footer>
    <h4 class="text-center">CopyRight/2020</h4>
   </footer>

kblog/templates/header.html
   <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'okayama:index' %}">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          　{% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:detail' request.user.id %}">{{request.user.username}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'okayama:add' %}">投稿</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:signup' %}">新規登録</a>
          </li>
     
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_app:login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

kblog/templates/okayama/about.html
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('/static/img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

kblog/templates/okayama/add.html
{% extends 'base.html' %}
{% load widget_tweaks %} <!-- 追加 -->
{% block content %}
<h1 class="mt-5 pt-4 text-center">新規投稿</h1>
<form action="{% url 'okayama:add' %}" method="POST" enctype="multipart/form-data">
 {% csrf_token %}

 <label for="id_title" class="sr-only">タイトル</label>
 <input type="text" name="title" placeholder="タイトル" maxlength="50" class="form-control mb-3" required id="id_title">

 <label for="id_text" class="sr-only">本文</label>
 <textarea type="text" name="text" placeholder="本文" cols="40" rows="10" class="form-control mb-3" required id="id_text"></textarea>

 <div class="mb-3 form-control text-secondary">
   <label>画像</label>
       {{ form.image }}
   </div>
     
 <div class="mb-3">
   <label for="id_tag" class="sr-only">タグ</label>
   {{ form.tag|add_class:"custom-select" }}
 </div>

 <button type="submit" class="btn btn-block btn-outline-success">投稿する</button>
</form>
{% endblock %}

kblog/templates/okayama/contact.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="post.html">Sample Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/contact-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </form>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

kblog/templates/okayama/detail.html
{% extends 'base.html' %}
{% block content %}   

 <!-- Page Header -->
 <header class="masthead" style="background-image: url('img/post-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1>本日は晴天なり、テストです</h1>
          <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
          <span class="meta">Posted by
            <a href="#">Start Bootstrap</a>
            on August 24, 2019</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        <h3 class="card-title font-weight-bold text-left">{{ post.title }}</h3>
        <p class="card-text">{{ post.text }}</p>
        <p>#{{post.tag}}</p>
        <p>{{post.created_at}}</p>


        {% if request.user == post.user %} 
   <a href="{% url 'okayama:edit' post_id=post.id %}"><button type="button" class="btn btn-outline-primary">編集</button></a>
   <a href="{% url 'okayama:delete' post_id=post.id %}"><button type="button" class="btn btn-outline-danger">削除</button></a>
   {% endif %}


        <!-- <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

        <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

        <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>

        <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

        <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

        <h2 class="section-heading">The Final Frontier</h2>

        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

        <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>

        <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>

        <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>

        <h2 class="section-heading">Reaching for the Stars</h2>

        <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>

        <a href="#">
          <img class="img-fluid" src="img/post-sample-image.jpg" alt="">
        </a>
        <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>

        <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>

        <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>

        <p>Placeholder text by
          <a href="http://spaceipsum.com/">Space Ipsum</a>. Photographs by
          <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>.</p> -->
      </div>
    </div>
  </div>
</article>

<hr>






<!-- <div class="card text-secondary" style="margin-top: 55px;">
 {% if post.image %}
 <img style="width: 100%; max-height: 500;" class="img-fluid mx-auto" src="{{ post.image.url }}">
 {% else %}
 <div class="p-1 border border-secondary text-center pt-5" style="min-width: 500; min-height: 400;">No Image</div>
 {% endif %}  <div class="card-body">
   <h3 class="card-title font-weight-bold text-center">{{ post.title }}</h3>
   <div class="p-3">
   <p class="card-text">{{ post.text }}</p>
   <p>#{{post.tag}}</p>
   <p>{{post.created_at}}</p>
   {% if request.user == post.user %} 
   <a href="{% url 'okayama:edit' post_id=post.id %}"><button type="button" class="btn btn-outline-primary">編集</button></a>
   <a href="{% url 'okayama:delete' post_id=post.id %}"><button type="button" class="btn btn-outline-danger">削除</button></a>
   {% endif %}
</div>
</div>
</div> -->
{% endblock %}

kblog/templates/okayama/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">編集</h1>
<form method="POST" enctype="multipart/form-data">
 {% csrf_token %}

 <label for="id_title" class="sr-only">タイトル</label>
 {{ form.title|add_class:"form-control mb-3"}}
 <label for="id_text" class="sr-only">本文</label>
 {{ form.text|add_class:"form-control mb-3"}}

 <div class="mb-3 form-control text-secondary">
   <label>画像</label>
       {{ form.image }}
   </div>

 <div class="my-5">
   <label for="id_tag" class="sr-only">タグ</label>
   {{ form.tag|add_class:"custom-select" }}
 </div>

 <button type="submit" class="btn btn-block btn-outline-success">編集する</button>
</form>

{% endblock %}

kblog/templates/user_app/detail.html
{% extends 'base.html' %}
{% block content %}   
<h1 class="text-center my-5">{{ user.username }}のページ</h1>
{% if request.user == user %}
 <div class="text-center"><a href="{% url 'user_app:edit' user_id=user.id %}"><button type="button" class="btn btn-outline-info">{{user}} 編集</button></a></div>
{% endif %} 

<div class="d-flex justify-content-center flex-wrap">


 {% for post in posts%}
 <a href="{% url 'okayama:detail' post_id=post.id %}">
   <div class="card m-4" style="min-width: 300; max-height: 490;">
     {% if post.image %}
     <img style="max-width: 300; max-height: 300;" class="card-img-top" src="{{ post.image.url }}">
     {% else %}
     <div class="p-1 border border-secondary text-center pt-5" style="min-width: 300; min-height: 225;">No Image</div>
     {% endif %}
     <div class="card-body">
       <h4 class="card-title">{{post.title|truncatechars:10 | linebreaksbr}}</h4>
       <p class="card-text">
         {{ post.text|truncatechars:17 }}
       </p>
     </a>
       <p>#{{post.tag}}</p>
       <p>{{post.created_at}}</p>
       
   </div>
 </div>
 {% endfor %}
 </div>
{% endblock %}

kblog/templates/user_app/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">{{user.username}}を編集</h1>
 <form class="form-signin" method="post">
   {% csrf_token %}

   <label for="id_username" class="text-secondary">名前</label>
   {{ form.username|add_class:"form-control mb-3" }}

   <label for="id_email" class="text-secondary">メールアドレス</label>
   {{ form.email|add_class:"form-control mb-3"}}

   <label for="id_password1" class="text-secondary">新しいパスワード</label>
   {{ form.password1|add_class:"form-control mb-3"}}

   <label for="id_password2" class="text-secondary">パスワード(確認用)</label>
   {{ form.password2|add_class:"form-control mb-3"}}

   <button type="submit" class="btn btn-block btn-outline-success">編集</button>
 </form> 

 <!-- 追加 -->
 {% if request.user == user %}
 <a href="{% url 'user_app:delete' user_id=user.id %}"><button type="button" class="btn btn-outline-danger">退会する</button></a> 
 {% endif %}
 <!-- ここまで --> 

{% endblock %}

kblog/templates/user_app/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">Login</h1>
<form method="post">
{% csrf_token %}
<label for="id_username" class="sr-only">ユーザー名</label>
<input type="text" name="username" placeholder="ユーザー名" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="form-control mb-3" required id="id_username">

<label for="id_password" class="sr-only">パスワード</label>
<input type="password" name="password" autocomplete="current-password" placeholder="パスワード" class="form-control mb-3" required id="id_password">

<button type="submit" class="btn btn-block btn-outline-success">Login</button>
</form>
{% endblock %}

kblog/templates/user_app/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">Signup</h1>
 <form class="form-signin" method="post">
   {% csrf_token %}
   <label for="id_username" class="sr-only">タイトル</label>
   <input type="text" name="username" placeholder="名前" maxlength="150" class="form-control mb-3" required id="id_username" autofocus>

   <label for="id_email" class="sr-only">メールアドレス</label>
   <input type="email" name="email" placeholder="メールアドレス" maxlength="254" class="form-control mb-3" required id="id_email">

   <label for="id_password1" class="sr-only">パスワード</label>
   <input type="password" name="password1" placeholder="パスワード" autocomplete="new-password" class="form-control mb-3" id="id_password1">

   <label for="id_password2" class="sr-only">パスワード(確認用)</label>
   <input type="password" name="password2" placeholder="パスワード(確認用)" autocomplete="new-password" class="form-control mb-3" required id="id_password2">

   <button type="submit" class="btn btn-block btn-outline-success">Signup</button>
 </form>
  <p>既にアカウントをお持ちですか?? <a href="{% url 'user_app:login' %}">Login</a></p>
</div>
</div>
{% endblock %}